"""Migrate

Revision ID: 486db7bd4526
Revises: fdf7278d0af5
Create Date: 2024-10-11 19:13:31.190854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '486db7bd4526'
down_revision = 'fdf7278d0af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'comments', ['comment_id'], ['id'])
        batch_op.create_foreign_key(None, 'blog_posts', ['post_id'], ['id'])
        batch_op.drop_column('target_type')
        batch_op.drop_column('target_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('target_type', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('comment_id')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
